project_id = "hxghysaqvzothpjfdxyw"

[functions.transcribe-audio]
verify_jwt = false

[functions.generate-with-ai]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.openai-realtime-session]
verify_jwt = false

[functions.generate-doctor-images]
verify_jwt = false
